---
- name: Operating system dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
- name: Python cryptography module
  pip: name=cryptography
- name: Letsencrypt Python client
  git: dest=/opt/letsencrypt clone=yes repo=https://github.com/letsencrypt/letsencrypt force=yes
